### ISSUE TITLE
Visual Studio 2022 support

### ISSUE THREAD

**Issue by stephenmcd1** [JapNolt/TfsPendingChangesMargin#3]
I've been working on adding support for VS 2022 for this extension.  This particular fork seemed to be the most active.  Would it make sense to contribute my changes back here?  Otherwise, I can make yet another fork of my own.

**Comment by JapNolt** [comment]
I haven't thought about this extension for several years (I've moved to using Git repos). I would suggest making your own fork. Cheers!!

**Comment by stephenmcd1** [comment]
Sounds good.  I've forked your repo [here](https://github.com/stephenmcd1/TfsPendingChangesMargin) and published an updated version of the extension for VS2022 in case any future people come across this.  See: https://marketplace.visualstudio.com/items?itemName=StephenMcDaniel.TfsPendingChangesMargin-VS2022
